title: JavaScript entwerfen.
lang: de
navigation:
  TC39:
    title: TC39
    agenda: Bevorstehende Agenda
    notes: Notizen der letzten Sitzung
    sub-menu: TC39 Untermenü umschalten
  specs:
    title: Spezifikationen
    proposals: Aktive Vorschläge
    ecma-262: ECMA-262, ECMAScript
    ecma-402: ECMA-402, Intl API
    sub-menu: Spezifikationen Untermenü umschalten
  contribute:
    title: Mitmachen
    proposals: Zu Vorschlägen beitragen
    tests: Zu Tests beitragen
    read: Lesen der Spezifikation
    discourse: An Diskussionen teilnehmen
    sub-menu: Mitmachen Untermenü umschalten
  state-of-proposals: Vorschläge
  skip-content: Zum Inhalt springen
  open: Menü öffnen
footer:
  connect: Verbinden
  contribute: Mitmachen
  standards: Standards
  proposals: Vorschläge
  archives: Archiv
  process: Prozess
  coc: Code of Conduct
  feedback: Wir sind auf der Suche nach Feedback.
  feedback-prompt: Bitte öffnen Sie <a href="https://github.com/tc39/tc39.github.io/issues/new" target="_blank">ein Issue </a> in <a href="https://github.com/tc39/tc39.github.io" target="_blank">unserem Website-Repository</a>.
links:
  coc: https://tc39.es/code-of-conduct
  process: https://tc39.es/process-document
  contribute-to-proposals: https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md
  contribute-to-tests: https://github.com/tc39/test262/blob/master/CONTRIBUTING.md
  discourse: https://es.discourse.group/
